### ISSUE TITLE
Spec API for screenshot service

### ISSUE THREAD

**Issue by simonwex** [mozilla/screenshots-delete-me#2]
For reference, here's the documentation for the [webmaker-screenshot](https://github.com/toolness/webmaker-screenshot) service that's currently hosted at [webmaker-screenshot.herokuapp.com](http://webmaker-screenshot.herokuapp.com/):

> Given a make at:
>
>     https://toolness.makes.org/thimble/LTcwNzI2NDUxMg==/example
>
> The screenshot can be found at:
>
>     https://webmaker-screenshot.herokuapp.com/toolness.makes.org/thimble/LTcwNzI2NDUxMg==/example
>
> In other words, just remove the `https://` at the beginning of the make and
> add it to the root of the web service.
>
> If the screenshot doesn't already exist, it will be created on-the-fly.
> Then the client will be redirected to the screenshot's location on S3.
> 
> If a screenshot becomes out-of-date, you can forcibly regenerate it using
> the form at the root of the website. Alternatively, issue a `POST`
> request to the root of the website with the `url` parameter set to the
> URL of the make.

**Comment by simonwex** [comment]
Hey @toolness where's the code for this?

**Comment by toolness** [comment]
Ack, sorry, it's here right now:

https://github.com/toolness/webmaker-screenshot

I should move it to one of the mozilla orgs, though. I assume I should move it to `mozilla`, and not `MozillaFoundation`?

I could also just import everything into this mozilla/screenshots repo, though there are a few issues in my original repo that would be easier to migrate if I just transferred ownership instead of importing.

**Comment by simonwex** [comment]
@toolness could you move it into the `mozilla` org? I'll delete this repo.

**Comment by toolness** [comment]
Sure, just did it... it said it would take a few minutes. I gave a bunch of teams access to it ... basically anything with the word 'mofo' or 'webmaker' in it.

**Comment by simonwex** [comment]
Great. 

This repo will self-destruct.
